timeout: 2700s  # 45 minutes

options:
  machineType: N1_HIGHCPU_8

steps:

- name: python:3.9
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace

    # Install bazel
    apt install -y apt-transport-https curl gnupg    
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
    mv bazel.gpg /etc/apt/trusted.gpg.d/
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
    apt update
    apt install bazel-3.4.1
    alias bazel=bazel-3.4.1


    # Check versions
    python --version
    bazel --version

    bazel build //package_manager:dpkg_parser.par

    # Optional: trigger building package bundles without concurrency to avoid
    # flakiness: https://github.com/GoogleContainerTools/distroless/issues/646
    bazel build --jobs=1 @package_bundle_amd64_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm64_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_s390x_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_ppc64le_debian10//file:packages.bzl

    bazel build --jobs=1 @package_bundle_amd64_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm64_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_s390x_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_ppc64le_debian11//file:packages.bzl

    bazel run //:publish
    bazel build all.tar

- name: docker
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  entrypoint: ./cloudbuild_docker.sh

- name: ubuntu
  entrypoint: ./cloudbuild_jq.sh

- name: gcr.io/projectsigstore/cosign:v0.6.0@sha256:2303322158802ec0452758578ac80801a3754ee9cb19c128fc5d1b2ec32fa2d2
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  entrypoint: sh
  args:
  - ./cloudbuild_cosign.sh 
