apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: distroless-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/GoogleContainerTools/distroless
    - name: revision
      value: ${COMMIT}
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-distroless
spec:
  taskRef:
    name: build-distroless
  resources:
    inputs:
    - name: source
      resourceRef:
        name: distroless-git
  