apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: distroless-build-task
  annotations:
    description: |
      A task that will run the build for this repo
spec:
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: git-repo
      image: ubuntu
      workingDir: /workspace/source
      script: |
        ls
        echo "This worked!"
