apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-distroless
spec:
  taskRef:
    name: build-distroless
  resources:
    inputs:
    - name: source
      resourceRef:
        name: distroless-git
  